import { Product } from './productGrid'

export const products: Product[] = [
  {
    id: 'aurora-lounge-chair',
    name: 'Aurora Lounge Chair',
    category: 'Furniture',
    price: 249,
    rating: 4,
    imageSeed: 'aurora-lounge-chair',
  },
  {
    id: 'nimbus-table-lamp',
    name: 'Nimbus Table Lamp',
    category: 'Lighting',
    price: 89,
    rating: 5,
    imageSeed: 'nimbus-table-lamp',
  },
  {
    id: 'drift-ceramic-vase',
    name: 'Drift Ceramic Vase',
    category: 'Decor',
    price: 34,
    rating: 3,
    imageSeed: 'drift-ceramic-vase',
  },
  {
    id: 'haven-throw-blanket',
    name: 'Haven Throw Blanket',
    category: 'Textiles',
    price: 59,
    rating: 5,
    imageSeed: 'haven-throw-blanket',
  },
  {
    id: 'lumen-pendant-light',
    name: 'Lumen Pendant Light',
    category: 'Lighting',
    price: 129,
    rating: 4,
    imageSeed: 'lumen-pendant-light',
  },
  {
    id: 'ridge-oak-shelf',
    name: 'Ridge Oak Shelf',
    category: 'Furniture',
    price: 179,
    rating: 4,
    imageSeed: 'ridge-oak-shelf',
  },
  {
    id: 'solace-linen-cushion',
    name: 'Solace Linen Cushion',
    category: 'Textiles',
    price: 42,
    rating: 3,
    imageSeed: 'solace-linen-cushion',
  },
  {
    id: 'echo-wall-mirror',
    name: 'Echo Wall Mirror',
    category: 'Decor',
    price: 149,
    rating: 5,
    imageSeed: 'echo-wall-mirror',
  },
  {
    id: 'juniper-storage-basket',
    name: 'Juniper Storage Basket',
    category: 'Decor',
    price: 45,
    rating: 4,
    imageSeed: 'juniper-storage-basket',
  },
  {
    id: 'cascade-floor-rug',
    name: 'Cascade Floor Rug',
    category: 'Textiles',
    price: 219,
    rating: 5,
    imageSeed: 'cascade-floor-rug',
  },
]
